# This is a basic workflow to help you get started with Actions

name: Delete repo pages

# Controls when the workflow will run
on: [workflow_dispatch]

jobs:
  publish:
    runs-on: ubuntu-latest
    
    permissions:
      pages: write
      contents: read
    
    strategy:
      fail-fast: false
      matrix:
        token: ['${GH_TOKEN}']

    env:
      GITHUB_API_BASE_URL: https://api.github.com

    steps:
      - uses: actions/checkout@v2

      - name: Delete Package Version [Organization]
        id: e
        continue-on-error: true
        run: |
          curl \
            -X DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/delete-repo/delete-repo.github.io/pages
